name: Build Percona Server 5.7 Docker Image
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Percona server version'
        default: '5.7.43-47.1'
        required: true
        type: string

jobs:
  build_images:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./percona-server-57/
          build-args: |
            PS_VERSION=${{ github.event.inputs.version }}
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/percona-server:5.7, ${{ secrets.DOCKERHUB_USERNAME }}/percona-server:${{ github.event.inputs.version }}